# Generated by Django 5.0.6 on 2024-06-04 05:57

import cloudinary.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('site', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
