# Generated by Django 4.2.10 on 2024-06-15 17:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_qrcodes_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='files'),
        ),
    ]
