# Generated by Django 4.2.10 on 2024-06-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_qrcodes_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='file_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
