# Generated by Django 4.2.10 on 2024-06-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='no',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
